### ISSUE TITLE
Blank text from others in hypno state not working

### ISSUE THREAD

**Issue by FlyingHesitation** [littlesera/LSCG#10]
Heya, 
we've trying around a lot to fix this, but haven't found any solition. When in a hypno state the messages from others are meant to be blank, but for some of us it wasn't working and we couldn't figure out why. I disabled all other add ons to find any conflicts, but even in vanilla with only LSCG it didn't work. 
Is there a certain vanilla setting or something that is required or is there a bug?

Thanks~

**Comment by littlesera** [comment]
@FlyingHesitation  I've heard this before but for the life of me couldn't get a repro. Could you send the original name and nicknames of the characters who are having trouble?

**Comment by FlyingHesitation** [comment]
> @FlyingHesitation I've heard this before but for the life of me couldn't get a repro. Could you send the original name and nicknames of the characters who are having trouble?

Original name: Ann
No nickname set.
Member number: 121901

**Comment by littlesera** [comment]
lol found it, silly assumption error. Should be fixed!

**Comment by FlyingHesitation** [comment]
Great thanks!
