### ISSUE TITLE
More configuration options for drugs

### ISSUE THREAD

**Issue by jimmyG1** [littlesera/LSCG#104]
being able to edit the settings like the decay rate and what not of the drugs

**Comment by jimmyG1** [comment]
and the longer you have cloraform over your mouth and nose it KOs you longer win it is removed

**Comment by Dwfreegethub** [comment]
I can see where that could fun. The drinks and the injections could use a different keywords for weak strong and extra strong. Or the more times you get injected or drink in a room the longer it lasts. 

Or this sounds way more complicated but is there a way to have a munu pop up when you use the injection for different strength?

Although on the cloraform I feel like there should be a max time before you have to put a new one on. Maybe after an hour  or something like that it gets weaker with a chance of waking up (mini game) and again every 15 minutes until you wake up..  And these could be options you can turn on and off as well..

**Comment by littlesera** [comment]
The drug implementation is on the incoming side. As in, an LSCG user with drugs enabled will be affected by anyone using a crafted injector or drink (can be drugged by vanilla BC users). For example, this means it doesn't currently support crafting your injector to be stronger, but we could support incoming injections of different levels.

**Comment by littlesera** [comment]
v0.1.10 includes a default max time for chloroform. This can be turned off (never wear off) in preferences.
