### ISSUE TITLE
Collar-agnostic choking

### ISSUE THREAD

**Issue by jimmyG1** [littlesera/LSCG#111]
a setting to make collars ato update to the new collar you have on

**Comment by littlesera** [comment]
The current design of the collar module is it is "attached" to a specific collar, so whenever you wear it it can be controlled (tightened/loosened). The above suggestion would be more of a "ignore collar specifics" kind of setting which is counter to the narrative of the current module. Will consider it, but will probably not implement for now.

As a follow up claification question are you switching collars frequently and want to be able to tighten/loosen regardless of which one you're wearing?

**Comment by jimmyG1** [comment]
yea i don't were the same collar all the time
