### ISSUE TITLE
LSCG and MBS interactions

### ISSUE THREAD

**Issue by anchillabc** [littlesera/LSCG#129]
When using a crafted respirator with appropriate keywords in an MBS outfit with a timed MBS sping, the expectation is that the the timer unlock will remove the respirator as well, but this does not seem to happen.

**Comment by anchillabc** [comment]
Small but important detail: the unlock removal happened AFTER the user had fallen asleep and was asleep during the unlock.

**Comment by littlesera** [comment]
Does it write the line:
"... mask hisses quietly as it runs out of its supply of gas."?

**Comment by littlesera** [comment]
Note: it appears that the latex respirator is unable to have a lock anyways, so MBS will not remove it when the other locks timeout. Tested this without LSCG enabled as well.

**Comment by anchillabc** [comment]
Oh I'm sorry for wasting your time - how did I miss that?
