### ISSUE TITLE
Multiple thoughts and potential bugs 

### ISSUE THREAD

**Issue by Dwfreegethub** [littlesera/LSCG#149]
If two people grab each other's arms it seems neither player can struggle to get away, or maybe only the first one to be grabbed. I witnessed this one but was not involved. Either way it throws things off until both let go and one person grabs. 

If a person has a ball gag necklace on and you put one on them via the LSCG action it confuses it. The only option you have after that is to move gag up and that doesn't work because they are already gagged. You do not have the option to put it back in your hand. The tradional way of removing it works.

If you are hypnotized and someone tries to steal something from you there is still a struggle and that seems confusing to me.  Or possibly it can be one behavior immersion vs regular?

Last one is a suggestion. Can we be able to put a crop in some on mouth. That seems obvious considering there is already a crop gag?

**Comment by littlesera** [comment]
In the future, go ahead and either start a discussion with multiple points, or make multiple issues for each one. It'll be easier to track.

- Managed to get a repro of the double arm grab, it's ephemeral but I'll look into it.
- I'm a little confused here. If someone is already wearing a necklace (necklace ballgag) you should not be able to "place around neck" a gag from your hand or "wear around neck" a gag from the mouth. I don't have a repro of what you're claiming here, maybe some more detail would help
- Yep, bug here. An incapacitated defender (hypno, drug asleep/brainwashed, chloroform asleep) should always lose those contests but that check appears to be broken. Will fix.
- You already can do this. The "place gag in mouth" activity checks the selected slot and if the gag is allowed. Try using the left mouth slot (ItemMouth) as that's the only one you can normally put a crop.
