### ISSUE TITLE
Head butts

### ISSUE THREAD

**Issue by Dwfreegethub** [littlesera/LSCG#194]
Can you please add an option for headbutts, Especially to the receiver head, have a chance to stun one or another of the people. I would say that the one doing the butting would have the lesser chance of being stunned, but still have a chance.

During stunned time some options, can't leave the room, cannot stop drinks, can't stand. 

Maybe they could even be cumulative and even knock some one out?  Although not as sure about that.

**Comment by littlesera** [comment]
Discussion threads are the preferred location for mod ideas. Migrating this there: #197
