### ISSUE TITLE
Performance option

### ISSUE THREAD

**Issue by dDeepLb** [littlesera/LSCG#23]
When hypnotized, that purple blur causes lagging. Add option to disable it. Or just it needs to be optimized.

**Comment by littlesera** [comment]
The bluring for hypno should be honoring your vanilla BC blur enabled setting

**Comment by littlesera** [comment]
https://github.com/littlesera/LSCG/blob/3ced78c3e9fe8146d648b243b129b41d9e44adee/src/Modules/hypno.ts#LL129C38-L129C38
