### ISSUE TITLE
Redesign module structure

### ISSUE THREAD

**Issue by littlesera** [littlesera/LSCG#266]
Modules could use a reorganization and refactor to better share settings/information for future development.

**State Module**
- Move all character "state" logic here
- Hypnotized, Asleep, Horny, Choking, Passout
- As few emote strings here as possible, just mechanic handling, hooks, and any interaction resolution between

Setting structure currently tied to old module naming... mostly.
- Move state-related settings under StateModule
  - Things like "Immersive" etc. (maybe make "Immersive" play apply to all states instead of per-'type')
- Migrator from old to new

Continue filling out here...

**Comment by jimmyG1** [comment]
i like the idea of haveing a "Immersive" play that just sets all the Immersive stuff on at wones

**Comment by Dwfreegethub** [comment]
I agree, one spot to enable immersive would make the most sense, if it doesn't cause you to have to go rewrite a lot of code.  I suspect most people playing immersive are turning it all on.

**Comment by littlesera** [comment]
I imagine all or none is the most likely case currently as well

**Comment by littlesera** [comment]
Refactored in #271
