### ISSUE TITLE
crash when blindfolded and hypnotized.

### ISSUE THREAD

**Issue by eeeesee** [littlesera/LSCG#275]

**Comment by eeeesee** [comment]
When I get hypnotized by the vr trance I get a crash report and then nothing works. If I click on my profile the chat screen turns black.```
----- UNHANDLED ERROR (IN BC) -----
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'Name')
Source: <url>/Scripts/Server.js:356:40
TypeError: Cannot read properties of undefined (reading 'Name')
    at ServerAppearanceBundle (<url>/Scripts/Server.js:356:40)
    at i (https://sidiousious.gitlab.io/bc-addon-loader/vendor/bcmodsdk.js:10:1230)
    at https://sidiousious.gitlab.io/bc-addon-loader/vendor/bcmodsdk.js:10:2533
    at ChatRoomCharacterUpdate (<url>/Screens/Online/ChatRoom/ChatRoom.js:2331:16)
    at i (https://sidiousious.gitlab.io/bc-addon-loader/vendor/bcmodsdk.js:10:1230)
    at https://sidiousious.gitlab.io/bc-addon-loader/vendor/bcmodsdk.js:10:2533
    at HypnoModule.EnforceEyes (https://littlesera.github.io/LSCG/bundle.js?v=1695476664683:1673:10)
    at HypnoModule.SetEyes (https://littlesera.github.io/LSCG/bundle.js?v=1695476664683:1657:15)
    at InjectorModule.Brainwash (https://littlesera.github.io/LSCG/bundle.js?v=1695476664683:6355:74)
    at InjectorModule.MiniGameEnd (https://littlesera.github.io/LSCG/bundle.js?v=1695476664683:6322:27)

----- Current context (most recent first) -----
> Function ServerAppearanceBundle hook chain exit
> Function ChatRoomCharacterUpdate hook chain exit
> Function DrawProcess hook chain exit
| Patched by: FBC
> Function DrawProcess hook from FBC
> Function GameRun hook chain exit
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function MainRun hook chain exit
> Animation frame
| time: 1326288.453

----- Debug report -----
Location: https://www.bondageprojects.elementfx.com/R96/BondageClub/
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
BC Version: R96
ModSDK Version: 1.1.0
Mods:
  - Fantastic Ultimate Solution to Addon Management (FUSAM): 8e48d361
    repository: https://gitlab.com/Sidiousious/bc-addon-loader
  - Bondage Club Responsive (BC Responsive): 0.4.9
    repository: https://github.com/dDeepLb/BC-Responsive
  - Little Sera's Club Games (LSCG): 0.2.6
    repository: https://github.com/littlesera/LSCG
  - Ultra Bondage Club (ULTRAbc): 2.1
    repository: https://github.com/tetris245/ULTRAbc
  - Mute's Bondage Club Hacks Collection (MBCHC): dev.8
    repository: https://code.fleshless.org/mute/MBCHC/
  - Bondage Club Extended (BCX): 0.9.7-727d4820
    repository: https://github.com/Jomshir98/bondage-club-extended
  - For Better Club (FBC): 4.50
    repository: https://gitlab.com/Sidiousious/bce.git
No known legacy mods detected.

----- BC state report -----
Mouse position: 987 574
Connected to server: true
Local time: 1695477981363
Server time: 1695477977951.43 (diff: -3411.57)
Screen: Online/ChatRoom
In chatroom: true
GLVersion: webgl2
Last received message: ChatRoomMessage (1695477978852)
Last sent message: ChatRoomChat (1695477981356)

----- ModSDK report -----
No warnings.
```

**Comment by dDeepLb** [comment]
@littlesera We checked, it happens at least when `hypnoEyeType` is something other than it should be. So maybe we need some validation?

**Comment by eeeesee** [comment]
It seems I had eyes set to 14 when there are only 13 types of eyes.
