### ISSUE TITLE
BUG: Invalid `"None"` expression

### ISSUE THREAD

**Issue by bananarama92** [littlesera/LSCG#3]
LSCG currently makes a few calls to `CharacterSetFacialExpression()` wherein it attempts to set expressions to `"None"` (see example below), which is not a valid expression. Assuming the intention here is to return to the default expression then you can pass `null` instead.

https://github.com/littlesera/LSCG/blob/f8bbae1a7847b0c15d1533ee7ba7b098423b1843/src/Modules/collar.ts#L300

**Comment by Wolfuky** [comment]
how do you use the addon because i cant figure it out and everything is enable

**Comment by littlesera** [comment]
Think I got them all!
