### ISSUE TITLE
Suggestions for new activities.

### ISSUE THREAD

**Issue by dDeepLb** [littlesera/LSCG#31]
- Slide with pussy (on penis)
- Scissors (with pussy, I think understandable)
- Tug on cheeks
- Tickle armpit

**Comment by meandred** [comment]
another suggestion for an action is take in pussy, and take in mouth, and take in ass, for female side of insertions

**Comment by zorgjbe** [comment]
The reverse activities are supposed to be in BC. I just had to force-disable them as the male work shook up things a bit too much to stabilize everything in a single beta period.

**Comment by littlesera** [comment]
LSCG already has "ride with pussy" and "ride with ass" for those reverse actions. If they're coming in vanilla BC, they'll be removed from the mod at that time.

**Comment by zorgjbe** [comment]
Oh really? I missed those while taking a look last time, and I'd be interested to know how you managed to handle them. I'm presently bringing my work up to date and overhauling the activity prerequisite so it's a bit less convoluted to track which ones applies to which side of an activity. Though to be honest, between the dialog changes and the new PortalLink stuff, I'll post-pone that to the following release so I don't get drowned in bug reports.

**Comment by littlesera** [comment]
backlogging for now.
