### ISSUE TITLE
Characters resetting height

### ISSUE THREAD

**Issue by MaksimBondarev** [littlesera/LSCG#314]
Characters constantly changing their height under effect of "enlarge" of "shrink" spells making them blink for a split second... like returning to base height then back under the effect of spell.

**Comment by anchillabc** [comment]
Causes a flicker like effect; does not happen on everyone. We tested to see if it had something to do with BCX curses, does not appear to be the case.

**Comment by littlesera** [comment]
Probably due to the point where I'm hooking in to set the height ratio. Probably won't be fully fixed for a while.

**Comment by anchillabc** [comment]
Interestingly, this consistently happens to some players, but not others.

**Comment by Katie1707** [comment]
It Always happens to me.
I am on Browser.

**Comment by Katie1707** [comment]
It always happens to me.
I am on browser.
Feel free to contact me if you want to know more things.

**Comment by anchillabc** [comment]
> It always happens to me. I am on browser. Feel free to contact me if you want to know more things.

A bit of additional info here: Katie is not on mobile and is using chrome.

**Comment by anchillabc** [comment]
Additional info: we may have found the culprit: when something is blinking, the flicker occurs.
Never had the issue, tried a shock collar on myself and shrunk myself; immediately started flickering in time to the blinking of the light of the collar.

**Comment by littlesera** [comment]
interesting, blinking light, not blinking eyelids?

**Comment by Katie1707** [comment]
I wear a Forbidden chastity bra.
Everytime the light blinks My characters hight flickers.

**Comment by littlesera** [comment]
Great data point, I'll try this when I have time to circle back!
