### ISSUE TITLE
Quaff on others

### ISSUE THREAD

**Issue by anchillabc** [littlesera/LSCG#325]
Trying to make others quaff my potions results in the message saying I'm the one quaffing it

`(Anchilla quaffs the Dispel Magic (potion bottle) in one gulp.)`
`(Anchilla [13+3] manages to get their Dispel Magic past Smoll Kitty VeiVei's [11-2] lips, forcing her to swallow it.)`
`(Smoll Kitty VeiVei gasps, blinking as the magic affecting her is removed.)`

**Comment by Dwfreegethub** [comment]
I can confirm I am seeing this as well, but only on dispell. I have not gone through all potion types, but the only one I saw it on was dispell magic
