### ISSUE TITLE
could the magic be made to stack

### ISSUE THREAD

**Issue by meandred** [littlesera/LSCG#326]
as in use a grow magic twice it works as 3X or 4X size? same with shrink

**Comment by Dwfreegethub** [comment]
I am not sure if it would make sense for grow or shrink to get larger or smaller personal. Any bigger and you would cover the person next to you. Time though might make sense for the time to be extended, as long as it doesn't go over the person's max time set.

Just my thoughts.

**Comment by littlesera** [comment]
I chose against stacking resizing specifically because much smaller or larger you start to disappear or overlap with other character/UI elements in a way that looks more broken than fun.
