### ISSUE TITLE
FR: Enchanted Pendants

### ISSUE THREAD

**Issue by neaton-lab** [littlesera/LSCG#338]
The idea would be that, similar to the potions, you'd be able to craft a pendant, or potentially similar items such as collars or chastity items, to have a spell on them. This would primarily be for the shrink/grow effects for those of us that would like one of those two to be our "default". 

It would probably be a good idea to limit this to just a spells that only have a select few effects, namely reducing, enlarging, blinding, deafening, gagged, arousing, and potentially outfit and polymorph. The effects that can't be placed on potions, along with dispel, would obviously not make sense for these items. Bane and bless could be added, though that would be up to the implementer. Hypnotizing, slumbering, and petrifying I would recommend not including, or if you do only having them behind a setting on the wearer.

**Comment by anchillabc** [comment]
This is a very nice idea, but which existing items are usable for this? I can't immediately think of one.

**Comment by neaton-lab** [comment]
There aren't any, hence why it's a feature request, not a bug report

**Comment by littlesera** [comment]
Linking this in to #327
