### ISSUE TITLE
sleep don't prevent removing items

### ISSUE THREAD

**Issue by meandred** [littlesera/LSCG#352]
is it intentional that sleep even immersive same with chloroform don't prevent struggling out of item?

**Comment by littlesera** [comment]
Regression from removing entire character access block.

**Comment by meandred** [comment]
just normally struggling, might of broke in the recent version

**Comment by meandred** [comment]
of BC

**Comment by littlesera** [comment]
@meandred I'm unable to reproduce this issue, do you have more details steps of your case? or screengrabs?

**Comment by meandred** [comment]
![Screenshot (1205)](https://github.com/littlesera/LSCG/assets/132040988/c3e8dc28-d134-4a71-bda9-9c99a00d5361)
![Screenshot (1206)](https://github.com/littlesera/LSCG/assets/132040988/627609cb-43b1-4249-951e-2003c99a44a7)

**Comment by meandred** [comment]
that is what I mean

**Comment by meandred** [comment]
it even lets me with immersive conditions enabled
![Screenshot (1207)](https://github.com/littlesera/LSCG/assets/132040988/fc38fbf8-65fc-46f7-8c52-3a8593def439)

**Comment by meandred** [comment]
I am using try to struggle out

**Comment by littlesera** [comment]
Not seeing this on my characters, all slots are blocked and struggling is impossible:
![image](https://github.com/littlesera/LSCG/assets/126942824/fed0b6d4-47e0-40d9-a3a4-cf3f5cf5bec7)

Do you get 'true' if you run the following in dev console?
```Player.LSCG.StateModule.states.find(s => s.type == "asleep").active```

**Comment by meandred** [comment]
could it being the beta version cause any issues?
![Screenshot (1208)](https://github.com/littlesera/LSCG/assets/132040988/70a39fc1-6204-48fa-a7d2-4132027feeaa)

**Comment by meandred** [comment]
method of loading is FUSUM if that helps

**Comment by meandred** [comment]
I doubt being on cheaters edition also would cause the issue

**Comment by meandred** [comment]
method of administration is drugs

**Comment by littlesera** [comment]
What version of LSCG do you have loaded (hover the little teal star to see)? Also the beta is released now, so just use .../R97/BondageClub/

**Comment by meandred** [comment]
at the time it was the most recent now one behind going to update it and see if it fixes

**Comment by meandred** [comment]
just tested with .3.19 and still have that issue, but haven't tried non cheaters yet

**Comment by meandred** [comment]
still shows in pure public
![Screenshot (1209)](https://github.com/littlesera/LSCG/assets/132040988/71a6eac6-614d-442d-a792-c7737434a309)

**Comment by meandred** [comment]
![Screenshot (1210)](https://github.com/littlesera/LSCG/assets/132040988/0ab7dfb0-a7a6-4530-a4a8-0059d4336c91)
so you can see the verson

**Comment by meandred** [comment]
is there by chance some setting in LSCG I am missing? or should it block that outright?

**Comment by littlesera** [comment]
Do you have any other mods running in that test? It should block item group access whenever a state with "Move" restriction is enabled ('asleep' being one of them). 9https://github.com/littlesera/LSCG/blob/698b57b57d9c70a47775485c642af6c9e078b093/src/Modules/states.ts#L262C23-L262C58)

if you run this in your dev console what do you get?
```Player.LSCG.StateModule.states.find(s => s.type == "asleep").active```
I'm guessing 'true' since I see the state overlay on your last screenshot.
Additionally, try running this in console with one of your inventory group slots selected and let me know if it's true or false:
```InventoryGroupIsBlocked(Player)```

**Comment by meandred** [comment]
seems I didn't have my unrestrict one disabled called allow stupid it is more powerful than UBC's and all others but I will never make it a script to share, as it would piss off asset designers due to allowing male items on female characters and female items on male characters, by items I mean items and clothes
![Screenshot (1212)](https://github.com/littlesera/LSCG/assets/132040988/4897998d-3bc9-4d49-9f40-ecbb1c271145)

**Comment by meandred** [comment]
and that seems to of been my issue

**Comment by meandred** [comment]
was indeed an issue on my side with a script I doubt I will ever update as it seems to be always compatible
