### ISSUE TITLE
Magic require whitelist option blocks casting magic on yourself.

### ISSUE THREAD

**Issue by lolboxik** [littlesera/LSCG#367]
Images just in case~

![Screenshot_1](https://github.com/littlesera/LSCG/assets/68982104/90ade2c4-817a-447b-b692-c2d9d3c716a3)
![Screenshot_2](https://github.com/littlesera/LSCG/assets/68982104/d5134308-15e1-4cff-998e-d8646656b783)

**Comment by littlesera** [comment]
lol good catch.
fixed in #369
