### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by lisel02** [littlesera/LSCG#370]
Hello, I am trying to report a bug that LSCG is currently having that once player logged in their account, they cannot do anything, including saying anything, interacting and else. The bug happened after player firstly used a customized potion with LSCG magic effect “Outfit” and “Polymorph”; then used an auto-release script from another player. The situation persists if anyone else with the plugins log onto account of ppl with the bug. They cannot even use addon manager. Bug persists with only LSCG plugin installed also. Player with bug has pop-up window containing following error codes:

PolymorphedState.ts:86 Uncaught TypeError: Cannot read properties of null (reading 'Polymorph')
    at PolymorphedState.StripCharacter (PolymorphedState.ts:86:28)
    at PolymorphedState.Recover (ItemBundleBaseState.ts:40:18)
    at PolymorphedState.Tick (BaseState.ts:93:22)
    at states.ts:220:48
    at Array.forEach (<anonymous>)
    at states.ts:220:33
    at i (bcmodsdk.js:4:1419)
    at bcmodsdk.js:4:2510
    at GameRun (Game.js:63:2)
at MainRun (Game.js:165:31)

Thank you for the help!

**Comment by littlesera** [comment]
fixed in #371

**Comment by littlesera** [comment]
#372
