### ISSUE TITLE
Noseplugs not disappearing

### ISSUE THREAD

**Issue by anchillabc** [littlesera/LSCG#379]
At the end of 2 minutes, the noseplugs cause the "...nose plugs fall out." message, but fail to actually disappear. Observed it multiple times now.

**Comment by littlesera** [comment]
No repro on my tests.. Can you provide more details on the gags used, and if there were any logout, room change, or rate limit interruptions?

**Comment by anchillabc** [comment]
This occurred without any room change / rate limit / logout and login or other activities likely to reset the timer. Also no curses, or messages about them reappearing. 
I've observed this with 2 outfits of mine so far: One with a large d...o / harness ballgag combo + GP-9 gas mask, and the other with a large d...o / ball gag / prison lockdown gag
However, when I tried both with an alt just now, both clear the noseplugs cleanly... and I observed both of these combinations fail to clear multiple times each before reporting, so now I'm wondering if it's related to something that was hotfixed in the club itself...

**Comment by littlesera** [comment]
Closing for now
