### ISSUE TITLE
Errors in 0.02 Version

### ISSUE THREAD

**Issue by Dwfreegethub** [littlesera/LSCG#42]
Love the new options but it seems that a comma (,) between the words is no longer working to separate. 

Also was seeing one person that would not stay in Hypnosys.. They would come out right away..

**Comment by littlesera** [comment]
Interesting, will try to look into it tonight/tomorrow. Do you have specific steps that caused the person to drop right out of hypnosis? What is their "hypnosis time" set to?

**Comment by Dwfreegethub** [comment]
Yes we narrow it down to a timer issue, but still seems like the comma
separator is acting up...  Thank you for all your work on this

**Comment by littlesera** [comment]
Yeah I see the timing issue now. I refactored to use the BC timing functions instead of just a bunch of setTimers, probably something in there. on it!

**Comment by littlesera** [comment]
Fixed the timing issue. For the trigger list, do you have cycling enabled? If so only one of the comma-separated trigger options will be 'active' at a time, rotating to a new one at the specified time after the last time you recovered from hypnosis.
