### ISSUE TITLE
Hypnosis trigger word in map mode 

### ISSUE THREAD

**Issue by Dwfreegethub** [littlesera/LSCG#423]
In the map mode you have to be a very short distance from each other to hear each other, but it doesn't matter where in the map you are if someone says your trigger word you will become hypnotized.  You won't know who said it and they get no notification they hypnotized you potentially creating a situation where you can be stuck in hypnosis. Hopefully the way maps limits the distance you can hear someone is easy to figure out, if not a workaround would just be to notify you that you hypnotized someone in the map.

**Comment by littlesera** [comment]
Fixed in #435
