### ISSUE TITLE
Remote options doesn't seem to work

### ISSUE THREAD

**Issue by Blitzerfnv** [littlesera/LSCG#43]
Any way I could've enable the remote option in the hypnosis, it doesn't seem to work, it keeps giving me "Setting is deactivated", even though it's active.

**Comment by littlesera** [comment]
Enabling remote access allows _other_ people to modify _your_ settings. Other things to check are your BC item permissions, override member ids, "remote access requires trance," and "remote access limited to hypnotizer"

**Comment by littlesera** [comment]
- [ ] Add more helpful tool tip when remote hypnosis is unavailable

**Comment by littlesera** [comment]
@Blitzerfnv are you able to see the more helpful messages now?
