### ISSUE TITLE
Gag actions bug

### ISSUE THREAD

**Issue by dDeepLb** [littlesera/LSCG#431]
Gag from hand and necklace is bugged. 
When you gag person with it, it doesn't change gag type.

**Comment by littlesera** [comment]
I presume you mean the ballgag color? I see an issue from necklace to hand. hand ballgag only has one color, necklace has two, and mouth gag has two in the opposite order so there's some color juggling there.

Let me know if this isn't what your talking about.

**Comment by dDeepLb** [comment]
No, I meant that when you're putting gag on someone with action, from hand or from necklace, it doesn't changes gag to "Tight" type.

**Comment by littlesera** [comment]
Ah, there's some code to handle that but looks like the "TypeRecord" property also needs setting. Lower priority as the gag just applies in default type.

**Comment by dDeepLb** [comment]
Also, sometimes I can't take off gag and take it into my hand🙄

**Comment by littlesera** [comment]
Don't have a repro on that one. Are you clicking on the right mouth slot? Is anything currently in your hand? Is there any gag on a higher slot preventing it from being removed?

**Comment by dDeepLb** [comment]
No, sometimes it works perfectly, sometimes not working at all.

**Comment by dDeepLb** [comment]
What is right mouth slot? Slot to the right and like correct? Anyway it doesn't matter because not one slot is working out of 3..

**Comment by littlesera** [comment]
Yeah, don't have a repro on that. I can put a ballgag in any of the three mouth slots and "take gag" into my hand on self and other.

**Comment by dDeepLb** [comment]
How can I check then prerequisites for truthiness in moment when I open action menu?

**Comment by littlesera** [comment]
https://github.com/littlesera/LSCG/blob/4de73b6463d847a9c1c552385ad093855c93fbf3/src/Modules/item-use.ts#L367C6-L367C6

Checks if there's an item that matches a defined gag type, that it's not locked, blocked, you have perm to remove it, and you have nothing in your hand iirc

**Comment by dDeepLb** [comment]
well, tested a little and i can't do it, because prereq test isn't running for my sub, but runs for me...

**Comment by dDeepLb** [comment]
Actually it's clear now what caused it. Restraints on gagged person. Arm restraints.. Doesn't UseHands prereq should count player prereqs🙂
