### ISSUE TITLE
X-ray seems to have some bug

### ISSUE THREAD

**Issue by meandred** [littlesera/LSCG#440]
![image](https://github.com/littlesera/LSCG/assets/132040988/7ef30b03-09b0-4050-852a-1d30c1dae23e)

**Comment by meandred** [comment]
that is after the effect ends

**Comment by meandred** [comment]
likely it lacks the code when ended to rehide hidden assets

**Comment by meandred** [comment]
fixible by a relog

**Comment by littlesera** [comment]
Fixed in #443
