### ISSUE TITLE
Attempts to call invalid functions resulting in warnings in console.

### ISSUE THREAD

**Issue by Shiranui-Izayoi** [littlesera/LSCG#445]
When either the stable or beta version of this addon is loaded something that it is modifying will attempt to call functions for various clothing items which doesn't exist. This results in the console outputting a ton of warnings. Doesn't cause any harm as it is just console warnings but thought I would mention it.

An example is `Attempted to call invalid function "AssetsHairAccessory1GiantBow1BeforeDraw"`

Just in case it is a browser specific issue I am running Firefox.

**Comment by littlesera** [comment]
Resolved in #449
