### ISSUE TITLE
VR headset no longer triggers or adds to hypnosis.

### ISSUE THREAD

**Issue by Sappermentti** [littlesera/LSCG#458]
Noticed this when one of my characters spun a wheel and got an outfit with VR and the trance state on. No hypnosis, nor did the purple bar start filling up. The two LSCG users beside me didn't seem to go under either. 

Did some testing on another character with various VR configurations but didn't achieve the desired result.
![image (1)](https://github.com/littlesera/LSCG/assets/44980100/69a3a15f-b1f9-4d39-a494-e651bfc0a2e4)

**Comment by littlesera** [comment]
I pushed changes to dev/beta branch, are you able to switch to that and test?

**Comment by Sappermentti** [comment]
Yes the beta version seems have it working alright.
