### ISSUE TITLE
BUG: clamped mouth in map rooms remains clamped despite moving away.

### ISSUE THREAD

**Issue by anchillabc** [littlesera/LSCG#462]
In map rooms, the expectation would be to have the ability to talk restored when a hand has been clamped over the mouth but the clamper or clampee have moved away from each other. This is not the case right now.

**Comment by littlesera** [comment]
lscg custom leashing should behave similarly to regular leashing in map rooms.

**Comment by littlesera** [comment]
Fixed in beta
