### ISSUE TITLE
Enhancement of nose plugs (don't know how to make suggestion, sorry)

### ISSUE THREAD

**Issue by SteelShaitan** [littlesera/LSCG#47]
Is it possible to give nose plugs same feature as injector? I mean check item craft name to give it ability to bypass LSCG feature "gag suffocation"? I just crafting now big set of restraints and I get an idea of giving nose plugs feature "nose tubes" to prevent from suffocation while being overkill gagged.

**Comment by littlesera** [comment]
Add the word "breathable" (case insensitive) to either the crafted name or description and you should be good to go now!
