### ISSUE TITLE
Game Crashes when clicking on the mouth slot of an ungagged player.

### ISSUE THREAD

**Issue by Anna940** [littlesera/LSCG#48]
Name: "Ballgagged",
					Func: (acting, acted, group) => {
						var location = acted.FocusGroup?.Name!;
						return !InventoryGet(acting, "ItemHandheld") && InventoryGet(acted, location)?.Asset.Name! == "BallGag";
						var item = InventoryGet(acted, location);
						if (item!.Property!.Effect!.indexOf("Lock") > -1)
							return false;
						return !InventoryGet(acting, "ItemHandheld") && item?.Asset.Name! == "BallGag";

**if (item!.Property!.Effect!.indexOf("Lock") > -1)** //returns null and leads to an exception and crash when player is not wearing a gag

**Comment by Dwfreegethub** [comment]
This seems to be happening to me as well and I am gaged. It was working
last night. Did anything else update over night. My Master thinks fbc
updated last night.

**Comment by littlesera** [comment]
Bad mistake, so sorry.
Thank you for the report, should be fixed and pushed as 0.0.5
