### ISSUE TITLE
Safewording with this plugin doesn't remove restraints

### ISSUE THREAD

**Issue by Kaira-Silvermist** [littlesera/LSCG#49]
As said on the tin. I tested safewording across a few plugins since for some reason it stopped, and this plugin being enabled completely prevents restraints from being removed. You still get removed from the room, but it doesn't remove restraints for some reason. I'd rather it be a toggle, instead of just blanket stopping restraint removal.

**Comment by littlesera** [comment]
So sorry, seemed like a strange interaction with the 'release' safe word.
Both revert and release should go through now (and clear you of any LSCG incapacitations) as well as the '/safeword' command.
