### ISSUE TITLE
Mult word triggers

### ISSUE THREAD

**Issue by rossmontgo** [littlesera/LSCG#5]
Want to start with Thank you for making this I've had a lot of fun thanks to you. 
Is there a chance the triggers can be made to be multiple words or a phrase? Like "Good Girl" or "Your getting sleepy" .
Not a big thing but I think it'd make the triggers more useful.

**Comment by littlesera** [comment]
Thank you! Phrases should now be supported. Note: commas are used to separate triggers, so will not work in a phrase.
