### ISSUE TITLE
Huge Lag when Blur is added to screen

### ISSUE THREAD

**Issue by EmilyBondage** [littlesera/LSCG#540]
Every time i breath horny gas or get hypnotized, it get very laggy.

I would also suggest an option to stop the screen blur complete

**Comment by littlesera** [comment]
There is a base BC setting that controls screen bluring on the second page of the graphics preferenced, and LSCG respects it:
![image](https://github.com/user-attachments/assets/0330f331-e23d-4098-8024-1b5ac02220da)

**Comment by EmilyBondage** [comment]
Thank you!
