### ISSUE TITLE
adding ".." when forced to say a phrase let's you speak "normally"

### ISSUE THREAD

**Issue by KuraikoKooriookami** [littlesera/LSCG#555]
Not sure if this is caused by BC itself or not, but when forced to say a phrase you can still speak mostly normally by adding ".." before the sentence causing the message to be send with only one "." 
Using this method you firstly avoid speaking the phrase and additional cause to trigger other peoples. 
The Suggestion doesn't counts as ended and you have to say the phrase sooner or later except with a forgot suggestion
![grafik](https://github.com/user-attachments/assets/09b9db03-86c3-433d-95c9-3e563e56f566)

**Comment by littlesera** [comment]
BC uses "." for actions so the speech block is not blocking them. Other prefixes that pass through are '*' for emoting, '/' for commands and '(' for OOC. I use similar logic to BCX for speech blocking and for now I would rather it be a little more lenient to ensure user commands/emotes/OOC pass through, but will think of alternative approaches around this case. In the end, it's an RP tool and if someone really wants to cheese their way out there are plenty of other easy methods too.
