### ISSUE TITLE
LSCG removes access to some activities.

### ISSUE THREAD

**Issue by Nicole-Evermore** [littlesera/LSCG#575]
As of today (Oct 7th), it seems since everything was working fine before about midnight my time, having LSCG loaded removes several activity buttons one the main page. Screenshot is attached to show the empty space where those activities should be.
Second screenshot is without LSCG loaded.
![IMG_2956](https://github.com/user-attachments/assets/72e8baec-e7be-4b93-8556-886f603cd099)
![IMG_2957](https://github.com/user-attachments/assets/2a54c719-dcc9-4ceb-a9ff-0cb626fb0922)
Browsers used: Firefox and Safari

**Comment by Nicole-Evermore** [comment]
I really hope this is fixed, I quite like the features of LSCG, but it irks me that it's causing loss of base features.

**Comment by KuraikoKooriookami** [comment]
As far as im aware, if you are under a spell which changes your outfit, it blocks you out from wardrobe, which causes the buttons to be hidden. encountered this as spells on me dont run out

**Comment by Nicole-Evermore** [comment]
Ah, what about the bottom four activities?

**Comment by Nicole-Evermore** [comment]
Update, the clearing spell worked to re-assert the missing activities, but I still think it's a bug that the bottom for activities are removed along with the wardrobe option.

**Comment by littlesera** [comment]
Looks like those 4 activities also require you to be able to change clothes to enter:
```
		if (Player.CanChangeOwnClothes() && MainHallAllow("Q")) DrawButton(1525, 745, 90, 90, "", "White", "Icons/MagicSchool.png", TextGet("MagicSchool"));
		if (Player.CanChangeOwnClothes() && Player.CanTalk() && MainHallAllow("N")) DrawButton(1645, 745, 90, 90, "", "White", "Icons/Poker.png", TextGet("Poker"));
		if (Player.CanChangeOwnClothes() && MainHallAllow("O")) DrawButton(1765, 745, 90, 90, "", "White", "Icons/Infiltration.png", TextGet("Infiltration"));
		if (Player.CanChangeOwnClothes() && MainHallAllow("P")) DrawButton(1885, 745, 90, 90, "", "White", "Icons/MovieStudio.png", TextGet("MovieStudio"));
```
you ought to see them unavailable if you are otherwise unable to change, like if you are already bound, or have a bcx rule that prohibits wadrobe access.
