### ISSUE TITLE
Rope item interactions

### ISSUE THREAD

**Issue by dDeepLb** [littlesera/LSCG#59]
Using coilled rope on mouth should put rope ball gag or that other. Using on nech should put neck rope.
So we need:
- Eyes
- Mouth
- Neck
- Arms (Done)
- Torso
- Pelvis (Done)
- Legs (Done)
- Ankles (Done)
- Feets
Where rope have some variations, default can be used or the most logical~

**Comment by littlesera** [comment]
The current activity uses the built in BC list of "hemp rope" locations (arms, legs, ankle, etc). The extended list (gag, neck, toes, suspension, etc) would have to be added+handled and will probably be a later task.
