### ISSUE TITLE
tamperproof and selftightening removing locks

### ISSUE THREAD

**Issue by Mai3119** [littlesera/LSCG#594]
It seems if an item an example an armbinder suit has in the description tamperproof and selftightening and the user struggles with the button the item tightens like it should but also removes the lock. This goes for owner locks, lover locks and the list goes on.

**Comment by littlesera** [comment]
I unfortunately am unable to reproduce this issue with the arbinder jacket (nor leather armbinder), with the lock applied as part of the crafting, nor with the lock added after applying the item...
Could you screengrab a video of the issue, or connect with me to observe it in-game?

**Comment by Mai3119** [comment]
Are you free right now, I have a room "Testing1" and I can show you what is happening.

**Comment by Mai3119** [comment]
![Glitch](https://github.com/user-attachments/assets/52ce9994-978a-4a79-be23-e9ff2ef0c7b8)

I believe I attached a screengrab of it, if not I have the full video clip of it.

**Comment by Mai3119** [comment]
In the gif you can see how the armbinder suit has a high security lock on it, after struggling by using the button and the suit then tightening the lock is then removed.
