### ISSUE TITLE
could a changelog be added per update?

### ISSUE THREAD

**Issue by meandred** [littlesera/LSCG#76]
each update seems to unless something obvious occurs be just a random hidden thing so could a changelog be added each update?

**Comment by jimmyG1** [comment]
or a beep like MBS

**Comment by littlesera** [comment]
There are notes on each release, the latest of which can be found here: https://github.com/littlesera/LSCG/releases/latest
Also linked in the wiki which is linked to from the in-game ui, but can work on making it more obvious.

**Comment by littlesera** [comment]
I believe things like MBS beeps use a bot account which is out of scope for my work, but will investigate solutions.
