### ISSUE TITLE
Minor wording error with scarf / bandana 

### ISSUE THREAD

**Issue by Dwfreegethub** [littlesera/LSCG#83]
When you put on the bandana on as a necklace and pull it up it up the message text shows bandana, but when you pull it down it shows scarf. And back to bandana when it moves up..  No problem with it working, just looks odd.

**Comment by littlesera** [comment]
Yeah, working to fix this. The issue is due to BC having different properties for the neck vs mouth vs hand items that are semantically the same, and their string substitution for 'UsedAsset' uses them.

**Comment by littlesera** [comment]
eg: when you wear the 'bandana' on your neck it is the "Bandana" asset, and when you "move to mouth" it maps to the visually similar asset on the mouth slot that is, unfortunately, the "Scarf" asset.

**Comment by Dwfreegethub** [comment]
Yes I saw this when testing, and figure that is what was causing the problem. it not a huge issue.
