### ISSUE TITLE
Issue but workaround (If you're getting crashes when setting up general settings)

### ISSUE THREAD

**Issue by Wynnie-JAG** [littlesera/LSCG#9]
Hello - 
I know the script is WIP, and it's really fantastic, but there has been a bug I've dealt with on my alts. When you run LSCG, Hypnosis settings are great, but General have reliably caused a crash. (If you want the crash report, let me know.)
I have figured out the workaround, which has worked reliably. 

**1. Configure the Hypnosis settings and use a trigger word. 
2. Exit the script setup and get triggered.
3. Come back to the LSCG setup and General settings should now be available without a crash.**

Again, let me know if you want the crash report.

**Comment by jimmyG1** [comment]
did not work all well it still is available on my main and that is what madders

**Comment by littlesera** [comment]
Ah I was afraid of this, thank you for the report. Looks like probably the same crash as #8 ?

**Comment by littlesera** [comment]
Merged better fix from @zorgjbe
