### ISSUE TITLE
Locked Script can cause server error : "Connection rejected : your connection has been rate limited"

### ISSUE THREAD

**Issue by Evangelion-001** [littlesera/LSCG#96]
First of all sorry not familiar with GIT  I was in a BC Room with a full public account someone hypnotized me and then locked my settings. Something else must have been done but now this account is unable to connect to club room, server is limiting the connections.
here is a screenshot i can provide. Didn't manage to catch the flux in wireshark but willing to reproduce bug if it can help.
Thanks in advance

![lcsg_bug](https://github.com/littlesera/LSCG/assets/65453924/efbce4cf-401d-4a8e-8ea2-d7d64073730e)

**Comment by littlesera** [comment]
Good find, I'll be trying to reproduce tomorrow as well.
